auto news/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using auto_news.Areas.HelpPage.ModelDescriptions;
using auto_news.Areas.HelpPage.Models;

namespace auto_news.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

auto news/Controllers/CrawlerController.cs
using auto_news.Models;
using auto_news.Ultil;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace auto_news.Controllers
{
    [Authorize(Roles = "admin")]
    public class CrawlerController : Controller
    {
        private AutoNewsDbContext _db = new AutoNewsDbContext();
        public ActionResult Index()
        {   
            return View("SourcesConfig");
        }


        #region News Sources CRUD

        [HttpPost]
        public JsonResult GetAllNewsSource()
        {
            try
            {
                var sources = _db.NewsSources.Select(i => new { Id = i.Id, Name = i.Name, Description = i.Description }).ToList();
                return Json(new { Result = "OK", Records = sources });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult CreateNewsSource(NewsSource source)
        {
            try
            {
                
                NewsSource s = _db.NewsSources.Add(source);
                _db.SaveChanges();
                return Json(new { Result = "OK", Record = s });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }

        [HttpPost]
        public ActionResult UpdateNewsSource(NewsSource source)
        {
            try
            {
                _db.Entry(source).State = EntityState.Modified;
                _db.SaveChanges();
                
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult DeleteNewsSource(int Id)
        {
            try
            {
                _db.NewsSources.Remove(_db.NewsSources.Find(Id));
                _db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        #endregion News Sources

        #region Category CRUD

        public JsonResult GetAllCategory()
        {
            try
            {
                var sources = _db.Categories.Select(i => new { Id = i.Id, Name = i.Name, Description = i.Description }).ToList();
                return Json(new { Result = "OK", Records = sources }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult CreateCategory(Category category)
        {
            try
            {

                Category s = _db.Categories.Add(category);
                _db.SaveChanges();
                return Json(new { Result = "OK", Record = s });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }

        [HttpPost]
        public ActionResult UpdateCategory(Category category)
        {
            try
            {
                _db.Entry(category).State = EntityState.Modified;
                _db.SaveChanges();

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult DeleteCategory(int Id)
        {
            try
            {
                _db.Categories.Remove(_db.Categories.Find(Id));
                _db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        #endregion Category CRUD


        #region CrawlConfig CRUD
        [HttpPost]
        public JsonResult CrawlConfigList(int sourceId)
        {
            try
            {
                var crawlConfigs = _db.CrawlConfigs.Where(c=>c.NewsSourceId==sourceId);
                return Json(new { Result = "OK", Records = crawlConfigs });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult DeleteCrawlConfig(int id)
        {
            try
            {
                _db.CrawlConfigs.Remove(_db.CrawlConfigs.Find(id));
                _db.SaveChanges();
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult UpdateCrawlConfig(CrawlConfig crawlConfig,string type)
        {
            try
            {
                _db.Entry(crawlConfig).State = EntityState.Modified;
                _db.SaveChanges();
                if (type == "update")
                {
                    return Redirect("/Crawler/PageCrawlConfig?type=update&id=" + crawlConfig.Id);

                }
                else return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult CreateCrawlConfig(CrawlConfig crawlConfig,string type)
        {
            try
            {
                var c = _db.CrawlConfigs.Add(crawlConfig);
                _db.SaveChanges();
                if (type == "add")
                {
                    return Redirect("/Crawler/PageCrawlConfig?type=update&id=" + c.Id);
                }
                else return Json(new { Result = "OK", Record = c });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        #endregion CrawlConfig CRUD
        public ActionResult PageCrawlConfig(int? id,string type)
        {    
            try
            {
                ViewBag.Type = type;

                var categories = _db.Categories.Select(i => i).OrderBy(i => i.Id);
                ViewBag.CategoriesId = JsonConvert.SerializeObject(categories.Select(i => i.Id).ToArray());
                ViewBag.CategoriesName = JsonConvert.SerializeObject(categories.Select(i => i.Name).ToArray());

                var newsSources = _db.NewsSources.Select(i => i).OrderBy(i => i.Id);

                ViewBag.NewsSourceIds = JsonConvert.SerializeObject(newsSources.Select(i => i.Id).ToArray());
                ViewBag.NewsSourceNames = JsonConvert.SerializeObject(newsSources.Select(i => i.Name).ToArray());

                if (type == "add")
                {
                    return View(new CrawlConfig());
                }
                else if(type=="update")
                {
                    var config = _db.CrawlConfigs.Find(id);
                    if (config != null)
                    {
                        return View(config);
                    }
                }
                return HttpNotFound();                
            }
            catch(Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
            
        }

        public ActionResult CategoriesConfig()
        {
            return View();
        }
     
        public ActionResult ScheduleJob()
        {
            MvcApplication.AutoNewsServiceInstance.ScheduleJob();
            return Json(new { status = "Ok" }, JsonRequestBehavior.AllowGet);   
        }

        

    }


}

auto news/Controllers/HomeController.cs
using auto_news.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

namespace auto_news.Controllers
{
    public class HomeController : Controller
    {
        private AutoNewsDbContext _db = new AutoNewsDbContext();
        public ActionResult Index()
        {
            return View();
        }

        [Route("detailArticle/{id:int}")]
        public ActionResult DetailArticle(int id)
        {
            var article = _db.Articles.Find(id);
            if (article != null)
            {
                return View(article);
            }
            else return HttpNotFound();
        }
    }
}

auto news/Views/Crawler/CategoriesConfig.cshtml
@section SPAViews {

<div id="CategoryTable" style="width: 100%; margin: auto;"></div>

}

@section Scripts{
    
    <link href="~/Scripts/jtable.2.4.0/themes/metro/blue/jtable.min.css" rel="stylesheet" />
    <script src="~/Scripts/jtable.2.4.0/jquery.jtable.min.js"></script>

    <script>
        $(document).ready(function () {
            
            $('#CategoryTable').jtable({
                title: 'Categories',
                actions: {
                    listAction: '/Crawler/GetAllCategory',
                    createAction: '/Crawler/CreateCategory',
                    updateAction: '/Crawler/UpdateCategory',
                    deleteAction: '/Crawler/DeleteCategory'
                },

                fields: {
                    Id: {
                        key: true,
                        list: false
                    },
                    Name: {
                        title: 'Tên',
                        width: '30%'
                    },

                    Description: {
                        title: 'Mô tả',
                        width: '30%'
                    }
                }
            });

            $('#CategoryTable').jtable('load');

    });
    </script>
}

auto news/Views/Crawler/PageCrawlConfig-old.cshtml
@section SPAViews {

   <form class="form-horizontal" role="form">
       <fieldset>
           <legend>Cấu hình chung</legend>

           <div class="form-group">
               <label class="col-sm-3 control-label">News Source</label>
               <div class="col-sm-9">
                   <select class="form-control" name="NewsSource">
                       <option value="0">Single Url</option>
                       <option value="1">List Url</option>
                       <option value="2">Generate Url</option>
                       <option value="3">From Api</option>
                   </select>
               </div>
           </div>

           <div class="form-group">
               <label class="col-sm-3 control-label">Category</label>
               <div class="col-sm-9">
                   <select class="form-control" name="Category">
                       
                   </select>
               </div>
           </div>

           
           <div class="form-group">
               
               <label class="col-sm-3 control-label" for="method">Method</label>
               <div class="col-sm-9">
                   <select class="form-control" name="crawlMethod" id="method">
                       <option value="0">Single Url</option>
                       <option value="1">List Url</option>
                       <option value="2">Generate Url</option>
                       <option value="3">From Api</option>
                   </select>
               </div>
           </div>
           
           <div id="methodDescription">
               <div method-id="0">
                   <div class="form-group">
                       <label class="col-sm-3 control-label">Url</label>
                       <div class="col-sm-9">
                           <input class="form-control" type="url" />
                       </div>
                   </div>
               </div>

               <div method-id="1">
                   <div class="form-group">
                       <label class="col-sm-3 control-label">List Url</label>
                       <div class="col-sm-9">
                           <textarea class="form-control"></textarea>
                       </div>
                   </div>
               </div>

               <div method-id="2">
                   <div class="btn btn-success form-group" id="add-param">Add Param</div><br /><br />
                   
                   <div class="form-group hidden" id="ParamItemTemplate">
                       <div class="btn btn-danger col-sm-1 remove-param" >X</div>
                       <label class="col-sm-1 control-label">Type</label>
                       <div class="col-sm-3">
                           <select class="form-control" name="paramType">
                               <option value="0">Fix</option>
                               <option value="1">Range</option>
                               <option value="2">List Value</option>
                               <option value="3">Categories</option>
                           </select>
                       </div>

                       <div id="paramDescription">
                           <div paramType-id="0">
                               <label class="control-label col-sm-1">Value</label> 
                               <div class="col-sm-3">
                                   <input class="form-control" type="text" />
                               </div>
                           </div>

                           <div paramType-id="1">
                               <label class="control-label col-sm-1">From</label>
                               <div class="col-sm-2">
                                   <input class="form-control" type="text" />
                               </div>
                               <label class="control-label col-sm-1">To</label>
                               <div class="col-sm-2">
                                   <input class="form-control" type="text" />
                               </div>
                           </div>

                           <div paramType-id="2">
                               <label class="control-label col-sm-1">List Value</label>
                               <div class="col-sm-4">
                                   <textarea class="form-control" ></textarea>
                               </div>
                           </div>

                           <div paramType-id="3">
                               <label class="control-label col-sm-1">Categories</label>
                               <div class="col-sm-4">
                                   <textarea class="form-control"></textarea>
                               </div>
                           </div>

                       </div>


                   </div>
              
               </div>
           </div>


        </fieldset>

           <fieldset>
               <legend>Trích lọc thông tin</legend>
               <div class="form-group">
                   <label class="col-sm-3 control-label">Title</label>
                   <div class="col-sm-9">
                       <input class="form-control" type="text" name="title" />
                   </div>
               </div>

               <div class="form-group">
                   <label class="col-sm-3 control-label">Description</label>
                   <div class="col-sm-9">
                       <input class="form-control" type="text" name="Description" />
                   </div>
               </div>

               <div class="form-group">
                   <label class="col-sm-3 control-label">ImageUrl</label>
                   <div class="col-sm-9">
                       <input class="form-control" type="text" name="ImageUrl" />
                   </div>
               </div>

               <div class="form-group">
                   <label class="col-sm-3 control-label">Content</label>
                   <div class="col-sm-9">
                       <input class="form-control" type="text" name="Content" />
                   </div>
               </div>
           </fieldset>
</form>

}



@section Scripts{
    <script>
        
        $(document).ready(function () {

            $("select[name='crawlMethod']").change(function () {
                var methodId = $(this).val();
                
                $("#methodDescription>div").hide();
                $("#methodDescription div[method-id='"+methodId+"']").show();
            });

            $("select[name='crawlMethod']").trigger("change");

            $("#add-param").click(function () {
                var e = $("#ParamItemTemplate").clone().removeClass("hidden");
                $(e).appendTo("div[method-id='2']");
                registerParamEvent(e);
            });


        });

        function registerParamEvent(e) {
            $(e).find(".remove-param").click(function () {
                $(this).closest(".form-group").remove();
            });

            $(e).find("select[name='paramType']").change(function () {
                var methodId = $(this).val();
                $(this).closest(".form-group").find("#paramDescription>div").hide();
                $(this).closest(".form-group").find("#paramDescription div[paramType-id='" + methodId + "']").show();
            });

            $(e).find("select[name='paramType']").trigger("change");

        }
    </script>
}

auto news/Views/Crawler/SchedulesConfig.cshtml
@section SPAViews {
    @Html.Partial("_Home")
}



@section Scripts{
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/app")
}

auto news/Views/Crawler/SourcesConfig.cshtml
@section SPAViews {



<div class="btn btn-info">
    <a style="color:white" href="/Crawler/PageCrawlConfig?type=add" target="_blank">
    Thêm cấu hình Crawl</a>
    </div>
  <br /><br />

<div id="NewsSourceTable" style="width: 100%; margin: auto;"></div>

}

@section Scripts{
    
    <link href="~/Scripts/jtable.2.4.0/themes/metro/blue/jtable.min.css" rel="stylesheet" />
    <script src="~/Scripts/jtable.2.4.0/jquery.jtable.min.js"></script>

    <script>
        $(document).ready(function () {
            
            $('#NewsSourceTable').jtable({
                title: 'Danh sách nguồn tin',
                actions: {
                    listAction: '/Crawler/GetAllNewsSource',
                    createAction: '/Crawler/CreateNewsSource',
                    updateAction: '/Crawler/UpdateNewsSource',
                    deleteAction: '/Crawler/DeleteNewsSource'
                },
                multiSorting: true,
                fields: {
                    Id: {
                        title:"Id",
                        key: true,
                    },
                    CrawlConfig: {
                        create: false,
                        edit: false,
                        title:'Nguồn tin',
                        width: "20%",
                        display: function(sourceData){
                            var $img = $('<span><img width="30px" src="https://cdn0.iconfinder.com/data/icons/gray-business-toolbar/512/repair-3-512.png" title="Edit Crawl Configs" />' + sourceData.record.Name+'</span>');
                            $img.click(function(){
                                $('#NewsSourceTable').jtable('openChildTable',
                                    $img.closest('tr'),
                                    {
                                        title:sourceData.record.Name,
                                        actions:{
                                            listAction: '/crawler/CrawlConfigList?sourceId=' + sourceData.record.Id,
                                            deleteAction: '/crawler/DeleteCrawlConfig',
                                            updateAction: '/crawler/UpdateCrawlConfig',
                                            createAction: '/crawler/CreateCrawlConfig'
                                        },
                                        fields:{
                                            NewsSourceId:{
                                                type:'hidden',
                                                defaultValue: sourceData.record.Id
                                            },
                                            Id: {
                                                title:"Id",
                                                key:true
                                            },
                                            IsScheduled:{
                                                title: 'Đã được lập lịch?',
                                                type: 'checkbox',
                                                values: { 'false': 'False', 'true': 'True' },
                                                defaultValue:'false'
                                            },
                                            Description:{
                                                title: 'Mô tả',
                                                display: function (crawlConfig) {
                                                    var $action = $('<a href="/Crawler/PageCrawlConfig?type=update&id='+crawlConfig.record.Id+'" target="_blank">Chỉnh sửa cấu hình</a>');
                                                    
                                                    return $action;
                                                }
                                            }

                                        }
                                    },function(data){
                                        data.childTable.jtable('load');
                                    });
                            });
                            return $img;
                        }
                    },
                    Name: {
                        title: 'Tên',
                        width: '30%',
                        list: false
                    },

                    Description: {
                        title: 'Mô tả',
                        width: '30%'
                    }
                    
                }
            });

            $('#NewsSourceTable').jtable('load');

    });
    </script>
}

auto news/Views/Crawler/_CrawlerMenu.cshtml
<ul class="nav nav-pills nav-stacked">
    <li><a href="/Crawler/Index">Nguồn tin </a></li>
    <li><a href="/Crawler/CategoriesConfig">Danh mục</a></li>
    <li><a href="/hangfire">Quản lý Jobs</a></li>
</ul>

auto news/Views/Crawler/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Cấu hình - Auto news</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Header", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Auto news", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Crawler", "Index", "Crawler", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:50px">
        <br />
        <div class="row">
            <div class="col-sm-3">
                @Html.Partial("_CrawlerMenu")
            </div>
            <div class="col-sm-9">
                @RenderBody()

                @RenderSection("SPAViews", required: false)
            </div>
        </div>
        
        
    </div>
    @*<div class="container">

        <footer class="footer">
            <hr />
            <p>&copy; @DateTime.Now.Year - Auto News</p>
        </footer>
    </div>*@
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)

    <script>
        
        $(document).ready(function () {
            $("a[href='" + window.location.pathname + "']").closest("li").addClass("active");
        });

    </script>  

</body>
</html>